# Generated by Django 4.1.7 on 2023-02-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
