# Generated by Django 4.1.7 on 2023-02-25 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Hotel',
            new_name='hotel',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
