# Generated by Django 4.1.7 on 2023-02-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_for_day',
            field=models.IntegerField(default=0),
        ),
    ]
