# Generated by Django 4.1.7 on 2023-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalprice',
            field=models.IntegerField(default=None),
        ),
    ]
