# Generated by Django 4.1.7 on 2023-02-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='totalprice',
        ),
    ]
