# Generated by Django 4.1.7 on 2023-02-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_price_for_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
