# Generated by Django 4.1.7 on 2023-02-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_for_day',
            field=models.CharField(choices=[('lux', 200), ('pollux', 150), ('standart', 100)], max_length=20),
        ),
    ]
