# Generated by Django 4.1.7 on 2023-02-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_price_for_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price_for_day',
            new_name='category',
        ),
    ]
