# Generated by Django 4.1.7 on 2023-02-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_price_for_day_booking_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='category',
            new_name='choi_room',
        ),
    ]
