# Generated by Django 4.1.7 on 2023-02-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_category_booking_choi_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='choi_room',
            new_name='category',
        ),
    ]
