# Generated by Django 4.1.7 on 2023-02-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_choi_room_booking_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
    ]
