# Generated by Django 4.1.7 on 2023-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
