# Generated by Django 4.1.7 on 2023-02-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_hotelrooms_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrooms',
            name='category',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(choices=[('lux', '200'), ('pollux', '150'), ('standart', '100')], decimal_places=5, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.category')),
            ],
        ),
    ]
