# Generated by Django 4.1.7 on 2023-02-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_hotelrooms_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_price', to='rooms.hotelrooms'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(choices=[('lux', '200'), ('pollux', '150'), ('standart', '100')], decimal_places=5, default=0, max_digits=5, max_length=30),
        ),
    ]
