# Generated by Django 4.1.7 on 2023-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(choices=[('lux', 200.0), ('pollux', 150.0), ('standart', 100.0)], decimal_places=2, default=0, max_digits=10),
        ),
    ]
