# Generated by Django 4.1.7 on 2023-02-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_price_room_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5, max_length=30),
        ),
    ]
