# Generated by Django 4.1.7 on 2023-02-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.category'),
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
