# Generated by Django 4.1.7 on 2023-02-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.ForeignKey(choices=[('lux', '200'), ('premium', '150'), ('standart', '100')], on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.category'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(choices=[('lux', '200'), ('premium', '150'), ('standart', '100')], decimal_places=5, default=0, max_digits=5, max_length=30),
        ),
    ]
