# Generated by Django 4.1.7 on 2023-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('lux', '200'), ('premium', '150'), ('standart', '100')], default=0, max_length=30),
        ),
    ]
