# Generated by Django 4.1.7 on 2023-02-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_alter_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.RemoveField(
            model_name='price',
            name='room',
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.category'),
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rooms.price'),
        ),
    ]
