# Generated by Django 4.1.7 on 2023-02-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_alter_hotelrooms_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
