# Generated by Django 4.1.7 on 2023-02-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotels_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image',
        ),
    ]
