# Generated by Django 4.1.7 on 2023-02-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Hotelsrooms',
            new_name='Hotel',
        ),
    ]
