# Generated by Django 4.1.7 on 2023-02-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_rename_hotelsrooms_rating_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
