# Generated by Django 4.1.7 on 2023-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
